### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by Liyx98** [OctoberChang/X-Transformer#14]
Hi~There are something wrong as  I run the code to get the datasets. So would you please give me a link to the datasets or send them to me as a file? thank you.

**Comment by OctoberChang** [comment]
You can also download the datasets from AttentionXML repo (https://github.com/yourh/AttentionXML), which is the same training/test set we are using. Sometimes there are download capacity limits in the goolge drive, you may try multiple times.

**Comment by Liyx98** [comment]
Thank you very much for your reply.

**Comment by shunshun-lala** [comment]
Hi, I have also found something wrong when I tried to get the data set. I read this comment and I'm confused about the difference between your datasets and ones from AttentionXML. There are no files named label_map.txt and files with postfix npz in the latter. How can I get these files? Thanks for your reply!

**Comment by shunshun-lala** [comment]
Hi, I'm wondering how you generate the file X.trn.npz, i.e. the instance TF-IDF feature matrix for the train set? Could you share your code about this process? Or is there any public code which have the same function? Thanks a lot!
