### ISSUE TITLE
What is the non-linear scoring function sigma to obtain final ranking?

### ISSUE THREAD

**Issue by vinaysetty** [OctoberChang/X-Transformer#16]
I realised you use a non-linear function called sigma to compute final ranking using the matcher score and ranker score using the OVA classifier. I didn't quite get what is this sigma function. I tried to search it in the code couldn't find it as well. Can you please define what it is?

**Comment by OctoberChang** [comment]
Details of the transformation function \sigma can be found in Eq(11) of the PECOS paper (https://arxiv.org/pdf/2010.05878.pdf). See the latest implementation (https://github.com/amzn/pecos/blob/mainline/pecos/xmc/base.py#L366).

**Comment by vinaysetty** [comment]
@OctoberChang Thanks for the answer! Can you say a bit about what is the difference to this new repository https://github.com/amzn/pecos? Do you recommend I should move to that repo for XMC?

**Comment by OctoberChang** [comment]
The PECOS repo (https://github.com/amzn/pecos) has the latest implementation of linear and neural models for XMC problems.
Training and inference are faster, and that repo will be maintained and updated frequently. 

Yes, I definitely recommend you use that repo for XMC.
