### ISSUE TITLE
Custom dataset tst.npz

### ISSUE THREAD

**Issue by hyperia-zeus** [OctoberChang/X-Transformer#5]
Greetings,

I am attempting to run X-Bert on a custom dataset but am confused regarding some of the steps.

The xbert.preprocess loads the mlc2seq (train/test/val) files in the dataset directory, generating a data_dict.pt and config.json file -- but the rest of the pipeline is expecting train/test/val.npz files.  I don't see any conversion between the data_dict and the tst.npz anywhere in the code -- am I missing a step?

Thanks for any help

**Comment by OctoberChang** [comment]
See the updated instruction: https://github.com/OctoberChang/X-Transformer#running-x-transformer-on-customized-datasets
