### ISSUE TITLE
X and Y .npz files for custom datasets

### ISSUE THREAD

**Issue by Cobollero** [OctoberChang/X-Transformer#6]
Hi! 

I'm trying to run X-BERT on a custom dataset, however I'm having trouble executing the Ranking step where I always get a ValueError('dimension mismatch') when running the ranker file. I think that this problem is due to the dimensions of the X and Y matrices stored in the npz files. 

This way, I would like to ask if you could release the code file that you used to create the different .npz files for your datasets so that I can correctly replicate them to my custom dataset.

Thanks

**Comment by OctoberChang** [comment]
We assume X and Y matrices are given. See more details on https://github.com/OctoberChang/X-Transformer#running-x-transformer-on-customized-datasets.
