### ISSUE TITLE
modeling.py : difference between RobertaForXMLC (etc.) class and transformers.RobertaForSequenceClassification?

### ISSUE THREAD

**Issue by simonlevine** [OctoberChang/X-Transformer#8]
Hi,
It's my understanding that the ForSequenceClassification variant is identical in function to the ForXMLC class defined in xbert/modeling.py.  Is this correct? Thanks!

**Comment by OctoberChang** [comment]
This repo may be out of date. Feel free to try out latest X-Transformer implementation at PECOS repo (https://github.com/amzn/pecos), thanks.
